---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: 01-Fetch a list of namespaces
      set_fact:
        projects: "{{ lookup('kubernetes.core.k8s', api_version='v1', kind='Namespace') }}"
    
    - name: 02-Fetch all deployments
      set_fact:
        deployments: "{{ lookup('kubernetes.core.k8s', kind='Deployment') }}"
    
    - name: 03-Fetch all deployments in a namespace
      set_fact:
        deployments: "{{ lookup('kubernetes.core.k8s', kind='Deployment', namespace='nginx') }}"
    
    - name: 04-Fetch with label selector
      set_fact:
        service: "{{ lookup('kubernetes.core.k8s', kind='Service', label_selector='app=nginx') }}"
