apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wildfly
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/volumes/wildfly"
