apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-wildfly
  namespace: wildfly
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: pv-wildfly
