---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:

    - name: Copy helm file
      ansible.builtin.copy:
        src: _build/helm
        dest: /usr/local/bin/helm
        owner: awx
        group: root
        mode: '755'

    - name: 01-Install Helm env plugin
      kubernetes.core.helm_plugin:
        plugin_path: https://github.com/adamreese/helm-env
        state: present

    - name: 02-Update Helm plugin
      kubernetes.core.helm_plugin:
        plugin_name: secrets
        state: latest

    - name: 03-Add bitnami chart repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: "https://charts.bitnami.com/bitnami"

    - name: 04-Create wildfly namespace
      kubernetes.core.k8s:
        name: wildfly
        api_version: v1
        kind: Namespace
        state: present

    - name: 06-Create PersistentVolume
      kubernetes.core.k8s:
        state: present
        src: 06-wildfly_pv.yaml

    - name: 07-Create PersistentVolumeClaim
      kubernetes.core.k8s:
        state: present
        src: 06-wildfly_pvc.yaml

    - name: 08-Deploy wildfly Helm
      kubernetes.core.helm:
        name: wildfly
        chart_ref: bitnami/wildfly
        release_namespace: wildfly
        values_files:
          - 06-wildfly-values.yaml
