---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: ensure python3 is installed
      become: yes
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
        state: present
    
    - name: install kubernetes pip package
      pip:
        name: kubernetes
        state: present
